### ISSUE TITLE
line-number plugin not working when using language-none

### ISSUE THREAD

**Issue by markg85** [PrismJS/prism#645]
Hi,

The line-number plugin only seems to be working if you set the highlighting to something other then none. While none is the advised one to use for plain text (if i read prismjs.com correctly).

What i "think" is going on is the hooks not being executed if highlighting wasn't used. Perhaps a simple fix would be to always execute the hooks?

Cheers,
Mark

**Comment by loganfranken** [comment]
Hey @markg85!

(Thanks for reporting this!)

I *think* this is the same problem that was discussed in #181: basically, (as @Golmote explains), the line numbers plugin runs in the `after-highlight` hook, which is never called because no highlighting occurs.

@Golmote lays out two approaches to fix this in #181: add a `no-grammar` hook or a `complete` hook. I think the latter approach makes the most sense.

I'm wondering if we should close #181 and have this be the main issue for this problem since #181 is actually about two different issues, the first of which we already solved.

(Let me know if you feel like I got this wrong, @markg85!)

**Comment by markg85** [comment]
hi @loganfranken,

You seem to be spot on. A "no-grammer" hook sounds a bit weird to me. I'd probably go for a "complete", "completed" or "done" hook which should probably be run when the core prismjs is done doing it's thing.

**Comment by Golmote** [comment]
Hi both of you.

I followed your advice, @loganfranken, and closed the other issue.

@markg85 I agree that the `complete` hook makes more sense than my other proposal. PRs are welcome to solve this issue, since I won't have much time during the next weeks to look into this. But I'll give it a try after my holidays if nobody did it in the meantime.

**Comment by markg85** [comment]
@Golmote I'm not quite familiar with how this script works and where it should be adapted. So I happily leave this to your (or anyone else who knows what needs to be done) capable hands :)

**Comment by Golmote** [comment]
This is fixed, as you can see in the last example on the [plugin page](http://prismjs.com/plugins/line-numbers/).

**Comment by brandoncc** [comment]
It still isn't working for me with the latest code downloaded from prismjs.com. Do I need to do something special to get it to work? I can't find any information on getting it to work.
